-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  type character varying DEFAULT 'shipping'::character varying CHECK (type::text = ANY (ARRAY['shipping'::character varying, 'billing'::character varying, 'both'::character varying]::text[])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  company text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  country text NOT NULL DEFAULT 'UG'::text,
  phone text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  event_type character varying NOT NULL,
  event_data jsonb DEFAULT '{}'::jsonb,
  page_url text,
  referrer text,
  user_agent text,
  ip_address inet,
  session_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  content text,
  excerpt text,
  featured_image text,
  author_id uuid,
  category character varying,
  tags ARRAY,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'archived'::character varying]::text[])),
  view_count integer DEFAULT 0,
  meta_title character varying,
  meta_description text,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  seo_title text,
  seo_description text,
  seo_keywords ARRAY,
  CONSTRAINT blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.business_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  email text,
  phone text,
  website text,
  description text,
  logo_url text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  country text DEFAULT 'United States'::text,
  tax_id text,
  currency text DEFAULT 'USD'::text,
  timezone text DEFAULT 'America/Los_Angeles'::text,
  language text DEFAULT 'English'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  image_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  slug character varying UNIQUE,
  sort_order integer DEFAULT 0,
  tags ARRAY,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  type character varying DEFAULT 'percentage'::character varying CHECK (type::text = ANY (ARRAY['percentage'::character varying, 'fixed_amount'::character varying]::text[])),
  value numeric NOT NULL CHECK (value >= 0::numeric),
  minimum_amount numeric DEFAULT 0,
  maximum_discount numeric,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customers_backup (
  id uuid,
  email text,
  first_name text,
  last_name text,
  full_name text,
  phone text,
  avatar_url text,
  date_of_birth date,
  gender text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  country text,
  total_orders integer,
  total_spent numeric,
  last_order_date timestamp with time zone,
  join_date timestamp with time zone,
  status text,
  preferences jsonb,
  notes text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.guest_customers_backup (
  id uuid,
  email character varying,
  name character varying,
  phone character varying,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  sku text UNIQUE,
  product_name text NOT NULL,
  category_name text,
  current_stock integer DEFAULT 0,
  min_stock integer DEFAULT 5,
  max_stock integer DEFAULT 100,
  reorder_point integer DEFAULT 10,
  unit_cost numeric,
  unit_price numeric,
  total_value numeric DEFAULT ((current_stock)::numeric * unit_cost),
  last_restocked timestamp with time zone,
  supplier text,
  status text DEFAULT 'in_stock'::text CHECK (status = ANY (ARRAY['in_stock'::text, 'low_stock'::text, 'out_of_stock'::text, 'discontinued'::text])),
  movement_trend text DEFAULT 'stable'::text CHECK (movement_trend = ANY (ARRAY['increasing'::text, 'decreasing'::text, 'stable'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.inventory_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  product_name text NOT NULL,
  adjustment_type text NOT NULL CHECK (adjustment_type = ANY (ARRAY['increase'::text, 'decrease'::text, 'set'::text])),
  quantity_before integer NOT NULL DEFAULT 0,
  quantity_after integer NOT NULL DEFAULT 0,
  quantity_change integer NOT NULL DEFAULT 0,
  reason text NOT NULL CHECK (reason = ANY (ARRAY['received'::text, 'damaged'::text, 'lost'::text, 'correction'::text, 'return'::text, 'sale'::text, 'transfer'::text, 'other'::text])),
  notes text,
  reference text,
  user_id uuid,
  user_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_adjustments_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_adjustments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_alert_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  low_stock_threshold integer NOT NULL DEFAULT 20 CHECK (low_stock_threshold >= 0 AND low_stock_threshold <= 100),
  critical_stock_threshold integer NOT NULL DEFAULT 5 CHECK (critical_stock_threshold >= 0 AND critical_stock_threshold <= 100),
  email_notifications boolean NOT NULL DEFAULT true,
  dashboard_notifications boolean NOT NULL DEFAULT true,
  notification_frequency text NOT NULL DEFAULT 'immediate'::text CHECK (notification_frequency = ANY (ARRAY['immediate'::text, 'daily'::text, 'weekly'::text])),
  email_recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
  auto_reorder_enabled boolean NOT NULL DEFAULT false,
  reorder_buffer_percentage integer NOT NULL DEFAULT 10 CHECK (reorder_buffer_percentage >= 0 AND reorder_buffer_percentage <= 100),
  category_specific_thresholds jsonb NOT NULL DEFAULT '{}'::jsonb,
  product_specific_thresholds jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inventory_alert_settings_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_alert_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  product_name text NOT NULL,
  product_sku text NOT NULL,
  physical_stock_before integer NOT NULL,
  physical_stock_after integer NOT NULL,
  reserved_stock_before integer NOT NULL,
  reserved_stock_after integer NOT NULL,
  available_stock_before integer NOT NULL,
  available_stock_after integer NOT NULL,
  operation_type text NOT NULL,
  operation_reason text,
  quantity_affected integer NOT NULL,
  order_id uuid,
  adjustment_id uuid,
  related_user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  inventory_version_before integer NOT NULL,
  inventory_version_after integer NOT NULL,
  CONSTRAINT inventory_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_audit_log_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_audit_log_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT inventory_audit_log_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  order_id uuid,
  quantity_reserved integer NOT NULL DEFAULT 0,
  reservation_type text NOT NULL CHECK (reservation_type = ANY (ARRAY['order'::text, 'hold'::text, 'transfer'::text, 'other'::text])),
  reason text,
  reserved_by uuid,
  reserved_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_reservations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_reservations_reserved_by_fkey FOREIGN KEY (reserved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  address text,
  city text,
  state text,
  country text DEFAULT 'Uganda'::text,
  postal_code text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  filename character varying NOT NULL,
  original_name character varying NOT NULL,
  file_path text NOT NULL,
  file_size integer NOT NULL,
  mime_type character varying NOT NULL,
  alt_text text,
  caption text,
  uploaded_by uuid,
  folder character varying DEFAULT 'uploads'::character varying,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  original_filename text,
  file_type text CHECK (file_type = ANY (ARRAY['image'::text, 'video'::text, 'document'::text, 'audio'::text])),
  CONSTRAINT media_pkey PRIMARY KEY (id),
  CONSTRAINT media_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  first_name text,
  last_name text,
  is_active boolean DEFAULT true,
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_fulfillment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  order_item_id uuid,
  product_id uuid,
  fulfilled_quantity integer NOT NULL CHECK (fulfilled_quantity > 0),
  fulfillment_date timestamp with time zone DEFAULT now(),
  fulfilled_by text,
  fulfillment_method text DEFAULT 'manual'::text CHECK (fulfillment_method = ANY (ARRAY['manual'::text, 'automated'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_fulfillment_pkey PRIMARY KEY (id),
  CONSTRAINT order_fulfillment_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_fulfillment_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT order_fulfillment_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_item_reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  order_item_id uuid,
  product_id uuid,
  reserved_quantity integer NOT NULL CHECK (reserved_quantity > 0),
  reserved_at timestamp with time zone DEFAULT now(),
  released_at timestamp with time zone,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'released'::text, 'fulfilled'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_item_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT order_item_reservations_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_item_reservations_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT order_item_reservations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  product_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  product_name text,
  product_sku text,
  unit_price numeric,
  total_price numeric,
  product_image character varying,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  note_type text DEFAULT 'general'::text CHECK (note_type = ANY (ARRAY['general'::text, 'customer'::text, 'internal'::text, 'fulfillment'::text, 'payment'::text, 'shipping'::text])),
  content text NOT NULL,
  is_internal boolean DEFAULT false,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_notes_pkey PRIMARY KEY (id),
  CONSTRAINT order_notes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.order_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  previous_status text,
  new_status text NOT NULL,
  previous_payment_status text,
  new_payment_status text,
  changed_by text,
  change_reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.order_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  task_type text NOT NULL CHECK (task_type = ANY (ARRAY['inventory_check'::text, 'payment_verification'::text, 'shipping_preparation'::text, 'quality_control'::text, 'customer_contact'::text, 'custom'::text])),
  title text NOT NULL,
  description text,
  assigned_to text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  completion_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT order_tasks_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  shipping_address text NOT NULL,
  billing_address text NOT NULL,
  payment_method character varying DEFAULT 'credit_card'::character varying,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying, 'partially_refunded'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  order_number character varying UNIQUE,
  subtotal numeric DEFAULT 0 CHECK (subtotal >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  shipping_amount numeric DEFAULT 0 CHECK (shipping_amount >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  payment_reference text,
  shipping_method character varying,
  tracking_number text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  customer_id uuid,
  customer_email text,
  customer_name text,
  currency text DEFAULT 'USD'::text,
  order_date timestamp with time zone DEFAULT now(),
  shipped_date timestamp with time zone,
  delivered_date timestamp with time zone,
  inventory_reserved boolean DEFAULT false,
  reserved_at timestamp with time zone,
  fulfilled_at timestamp with time zone,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  source text DEFAULT 'web'::text CHECK (source = ANY (ARRAY['web'::text, 'phone'::text, 'email'::text, 'walk_in'::text, 'marketplace'::text, 'admin'::text])),
  processing_notes text,
  fulfillment_status text DEFAULT 'unfulfilled'::text CHECK (fulfillment_status = ANY (ARRAY['unfulfilled'::text, 'partially_fulfilled'::text, 'fulfilled'::text, 'shipped'::text, 'delivered'::text])),
  version integer DEFAULT 1,
  guest_customer_id uuid,
  is_guest_order boolean DEFAULT false,
  customer_phone character varying,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  content text,
  excerpt text,
  meta_title character varying,
  meta_description text,
  featured_image text,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'published'::character varying, 'archived'::character varying]::text[])),
  template character varying DEFAULT 'default'::character varying,
  sort_order integer DEFAULT 0,
  is_homepage boolean DEFAULT false,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  seo_title text,
  seo_description text,
  seo_keywords ARRAY,
  author_id uuid,
  CONSTRAINT pages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  user_id uuid,
  order_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.product_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid,
  user_id uuid,
  ip_address inet,
  user_agent text,
  referrer text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_views_pkey PRIMARY KEY (id),
  CONSTRAINT product_views_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  category_id uuid,
  image_url text,
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  short_description character varying,
  sale_price numeric CHECK (sale_price >= 0::numeric),
  gallery_urls ARRAY,
  low_stock_threshold integer DEFAULT 10,
  sku character varying UNIQUE,
  weight numeric,
  dimensions jsonb,
  meta_title character varying,
  meta_description text,
  slug character varying UNIQUE,
  tags ARRAY,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'draft'::text, 'archived'::text])),
  featured boolean DEFAULT false,
  cost_price numeric,
  min_stock_level integer DEFAULT 5,
  max_stock_level integer DEFAULT 100 CHECK (max_stock_level > 0),
  reorder_point integer DEFAULT 10 CHECK (reorder_point > 0),
  images ARRAY,
  featured_image text,
  seo_title text,
  seo_description text,
  seo_keywords ARRAY,
  category_name text,
  location_id uuid,
  warehouse_id uuid,
  supplier_id uuid,
  reserved_quantity integer DEFAULT 0,
  available_quantity integer DEFAULT (stock_quantity - reserved_quantity),
  barcode text,
  notes text,
  last_restocked_at timestamp with time zone,
  last_sold_at timestamp with time zone,
  average_daily_sales numeric DEFAULT 0,
  reorder_quantity integer DEFAULT 0 CHECK (reorder_quantity > 0),
  safety_stock integer DEFAULT 0,
  abc_classification text DEFAULT 'C'::text CHECK (abc_classification = ANY (ARRAY['A'::text, 'B'::text, 'C'::text])),
  total_received integer DEFAULT 0,
  total_sold integer DEFAULT 0,
  total_adjusted integer DEFAULT 0,
  stock_turnover_rate numeric DEFAULT 0,
  days_in_stock integer DEFAULT 0,
  physical_stock integer DEFAULT 0 CHECK (physical_stock >= 0),
  reserved_stock integer DEFAULT 0 CHECK (reserved_stock >= 0),
  stock_status text DEFAULT 'in_stock'::text,
  inventory_version integer DEFAULT 1,
  last_stock_update timestamp with time zone DEFAULT now(),
  stock_hold_reason text,
  stock_hold_until timestamp with time zone,
  available_stock integer DEFAULT (physical_stock - reserved_stock),
  version integer DEFAULT 1,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT products_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  zip_code text,
  country text DEFAULT 'US'::text,
  is_admin boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  avatar_url text,
  date_of_birth date,
  gender character varying,
  is_verified boolean DEFAULT false,
  preferences jsonb DEFAULT '{}'::jsonb,
  last_login timestamp with time zone,
  bio text,
  location text,
  website text,
  timezone text DEFAULT 'America/Los_Angeles'::text,
  language text DEFAULT 'English'::text,
  notifications jsonb DEFAULT '{"sms": false, "push": true, "email": true, "marketing": true}'::jsonb,
  role character varying DEFAULT 'customer'::character varying,
  total_orders integer DEFAULT 0,
  total_spent numeric DEFAULT 0,
  last_order_date timestamp with time zone,
  join_date timestamp with time zone DEFAULT now(),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'blocked'::text])),
  notes text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reorder_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  alert_type text NOT NULL,
  current_stock integer NOT NULL,
  reorder_point integer NOT NULL,
  suggested_reorder_quantity integer,
  alert_status text NOT NULL DEFAULT 'active'::text CHECK (alert_status = ANY (ARRAY['active'::text, 'acknowledged'::text, 'resolved'::text, 'dismissed'::text])),
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  notes text,
  CONSTRAINT reorder_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT reorder_alerts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT reorder_alerts_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES auth.users(id)
);
CREATE TABLE public.sales_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL UNIQUE,
  total_revenue numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  total_customers integer DEFAULT 0,
  avg_order_value numeric DEFAULT 0,
  conversion_rate numeric DEFAULT 0,
  return_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid,
  product_name text,
  sku text,
  movement_type text CHECK (movement_type = ANY (ARRAY['in'::text, 'out'::text, 'adjustment'::text])),
  quantity integer,
  previous_stock integer,
  new_stock integer,
  reason text,
  reference text,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  product_id uuid,
  reference_type character varying,
  reference_id uuid,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_stock_movements_product_id FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT stock_movements_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.stock_reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  order_id uuid NOT NULL,
  quantity_reserved integer NOT NULL CHECK (quantity_reserved > 0),
  reservation_status text NOT NULL DEFAULT 'active'::text CHECK (reservation_status = ANY (ARRAY['active'::text, 'fulfilled'::text, 'cancelled'::text, 'expired'::text])),
  reserved_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  fulfilled_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_by uuid,
  notes text,
  CONSTRAINT stock_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT stock_reservations_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT stock_reservations_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT stock_reservations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  address text,
  city text,
  state text,
  country text DEFAULT 'Uganda'::text,
  postal_code text,
  payment_terms text,
  lead_time_days integer DEFAULT 7,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_carts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  session_id character varying UNIQUE,
  cart_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_carts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users_backup (
  id uuid,
  email character varying,
  name character varying,
  phone character varying,
  password_hash character varying,
  role character varying,
  is_guest boolean,
  email_verified boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  last_login timestamp with time zone
);
CREATE TABLE public.warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  location_id uuid,
  description text,
  capacity integer,
  current_utilization integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT warehouses_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.wishlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  product_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT wishlists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);